In [1]:
# You have a matrix MxN that represents a map. There are 2 possible states on the map: 1 -
# islands, 0 - ocean. Your task is to calculate the number of islands in the most effective way.
# Please write code in Python 3.
# Inputs:
# M N
# Matrix
# Examples:
# Input:
# 3 3
# 0 1 0
# 0 0 0
# 0 1 1
# Output: 2
# Input:
# 3 4
# 0 0 0 1
# 0 0 1 0
# 0 1 0 0
# Output: 3
# Input:
# 3 4
# 0 0 0 1
# 0 0 1 1
# 0 1 0 1
# Output: 2

In [2]:
#According to outputs, if island has another island in the neighborhood(right, left, bottom, top, BUT NOT DIAGONAL) 
#we recognize them as one 1 island

In [12]:
#create matrix with random values
import numpy as np

m, n = [int(x) for x in input().split()] #np.random.randint(1, 10), np.random.randint(1, 10)
island_map = np.zeros(shape=(m, n), dtype=int)

for row in range(m):
    for column in range(n):
        island_map[row, column] = np.random.randint(0, 2)

5 5


In [13]:
#islands detection
visited = []
count = 0

def dfs(i, j):
    if i < 0 or i >= m or j < 0 or j >= n or island_map[i][j] == 0 or (i, j) in visited:
        return None
    visited.append((i, j))
    #print(visited)
    
    dfs(i, j-1)
    dfs(i, j+1)
    dfs(i-1, j)
    dfs(i+1, j)
    
for i in range(m):
    for j in range(n):
        if island_map[i][j] == 1 and (i, j) not in visited:
            count += 1
            dfs(i, j)

print(f'size = {m, n}\n',
      f'matrix:\n{island_map}\n'
      f'number of islands: {count}')

size = (5, 5)
 matrix:
[[1 0 1 0 1]
 [0 1 0 0 0]
 [0 0 1 1 1]
 [1 0 0 1 0]
 [0 0 1 0 0]]
number of islands: 7
